theme: jekyll-theme-minimal
title: Antonio Ross
description: PhD student in Data Analytics and Society
linkedin: antonioross
img: https://github.com/Ant-Ross/Ant-Ross.github.io/images/rail_card_photo.JPG
